name: github-actions-test

on:
  push:
    branches:
    - main
    
jobs:

    test-job:
        runs-on: ubuntu-latest
        steps: 
        - name: First test step
          run: echo "Hello World" 
    

